### ISSUE TITLE
Question about the relation categories.

### ISSUE THREAD

**Issue by Boltzmachine** [131250208/TPlinker-joint-extraction#27]
I notice that you use argmax in your paper. But in the dataset, some entity pairs are labelled with multiple relations.  Such as Iceland and Reykjavik are labelled as "contain" and "capital". So how do you handle that if you only choose the one with the largest probability?

**Comment by 131250208** [comment]
Hi, thanks for your interest. In the paper, we assign one linear layer for each relation and use argmax for the output of every layer (to choose 1 or 0). In this way, we can handle multiple relations. It is not difficult to see this from Figure 3.

**Comment by Boltzmachine** [comment]
Thanks for reply. Another question is that why did you make all entities to be "DEFAULT" type. You did not recognize the type of entity?

**Comment by 131250208** [comment]
Because it is not necessary to recognize the type of entities for the relation extraction task since a predefined relation usually has fixed types for its subject and object. For example, ("place", "contains", "place") and ("country", "capital", "city"). If you need this feature, you can redefine the output tags of the EH-to-ET sequence or use TPLinkerPlus, which has already had this feature. If you use TPLinkerPlus, just set a specific entity type instead of "DEFAULT" in the entity_list.

**Comment by Boltzmachine** [comment]
That makes sense. Thank you very much.
