### ISSUE TITLE
the eval result

### ISSUE THREAD

**Issue by liutianling** [131250208/TPlinker-joint-extraction#7]
'time': 34.05615592002869,
 'val_ent_seq_acc': 0.8174603375650588,
 'val_f1': 0.7436676797886321,
 'val_head_rel_acc': 0.39087302432883353,
 'val_prec': 0.8524970963994364,
 'val_recall': 0.659478885893921,
 'val_tail_rel_acc': 0.40277778587880586

Current avf_f1: 0.7436676797886321, Best f1: 0.7436676797886321
I want to know how is the prec and the recall compute ? 
And the ent_seq_acc and the head_rel_acc, tail_rel_acc is considered ?

**Comment by 131250208** [comment]
See  MetricsCalculator() in the tplinker/tplinker.py. The ent_seq_acc, head_rel_acc, and tail_rel_acc are computed by get_sample_accuracy(), and they are not considered in computing precision and recall. They are accuracies of tag sequences, which means that a predicted tag sequence is correct only when the whole sequence is congruent to the golden tag sequence. You can get correct relations even though the tag sequence is not equal to the golden one, because some tags in the sequence might be already correct. So, they are just values for reference, have nothing to do with precision and recall. I am sorry that their names are kind of misleading. FYI, you can get a high f1 sore when these three accuracies are all over 0.9.

**Comment by 131250208** [comment]
The correct number, the precise number, and the golden number of relations are computed by get_rel_cpg(). The precision, recall, and f1 are computed by get_prf_scores(). They are all in the MetricsCalculator().

**Comment by liutianling** [comment]
Thanks very much for your reply.
Yes, I have trained on epoch 70 now, and the metric scores are very good. And it is still increasing . 

'time': 34.587841272354126,
 'val_ent_seq_acc': 0.8531746222149759,
 'val_f1': 0.8954688200486187,
 'val_head_rel_acc': 0.7321428775432564,
 'val_prec': 0.8942652329748302,
 'val_recall': 0.8966756513925519,
 'val_tail_rel_acc': 0.724206368660643}
Current avf_f1: 0.8954688200486187, Best f1: 0.8989578613001714

I will read the codes again and patient.
Thanks.

**Comment by 131250208** [comment]
No problem! Thanks for your attention to our work.

**Comment by pvcastro** [comment]
Hi @131250208 !
Sorry for reusing this issue, but I would like to discuss something further regarding these metrics :smile: 
I'm a bit confused due to the lack of a standardized metric and evaluation across these relation extraction benchmarks. Looks like all models I have evaluated so far are doing in their own way and comparing with each other's results, which doesn't seem so right to me. 
I have debugged your evaluation in MetricsCalculator and your model indeed seems to perform really well, comparing to others, but I get the feeling that maybe it would be more accurate to measure micro f1 considering the precision and recall for each category. 
Another issue I was wondering regarding your metrics...at the beginning of the training (and also at validation evaluation) you split your datasets set into smaller sequences (max_seq_length = 100 by default). When you do this, do you end up missing some relations from entities that get separated into different splits? Or do you something to prevent this? I realized that for test evaluation you use 512 for max_seq_length, so you don't actually miss anything when running the final test evaluation.
What are your thoughts on these?
Thanks, and congratulations for your work!

**Comment by 131250208** [comment]
> Hi @131250208 !
> Sorry for reusing this issue, but I would like to discuss something further regarding these metrics 😄
> I'm a bit confused due to the lack of a standardized metric and evaluation across these relation extraction benchmarks. Looks like all models I have evaluated so far are doing in their own way and comparing with each other's results, which doesn't seem so right to me.
> I have debugged your evaluation in MetricsCalculator and your model indeed seems to perform really well, comparing to others, but I get the feeling that maybe it would be more accurate to measure micro f1 considering the precision and recall for each category.
> Another issue I was wondering regarding your metrics...at the beginning of the training (and also at validation evaluation) you split your datasets set into smaller sequences (max_seq_length = 100 by default). When you do this, do you end up missing some relations from entities that get separated into different splits? Or do you something to prevent this? I realized that for test evaluation you use 512 for max_seq_length, so you don't actually miss anything when running the final test evaluation.
> What are your thoughts on these?
> Thanks, and congratulations for your work!

1. It would be more accurate to measure micro f1 considering the precision and recall for each category.
Yes, you are right. But for comparison with previous work, we just followed them and did not consider f1 on each category. We might add this part in the future. Thanks for your advice!
2. Do you end up missing some relations from entities that get separated into different splits?
We did not check if there are any entities separated into different splits. But we did apply some strategies to avoid missing. As you can see, we set the sliding length in the training because we use **a sliding window** to split the data. In this strategy, some of them might be split into different parts, but in another split, they have many chances to appear in the same part. So, you could try to change the sliding length, to see whether the performance is improved. I think it influences little if the dataset is big enought.

**Comment by pvcastro** [comment]
Ok, thanks @131250208 !
